nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization','X-Requested-With','withcredentials','Access-Control-Allow-Origin','Access-Control-Allow-Credentials','Access-Control-Allow-Headers']
            expose_headers: ['Link']
            max_age: 3600

        '^/api/login_check':
            allow_credentials: true
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization','X-Requested-With','withcredentials','Access-Control-Allow-Origin','Access-Control-Allow-Credentials','Access-Control-Allow-Headers']
            expose_headers: ['Link']
            max_age: 3600

        '^/':
            allow_origin: ['^http://localhost:[0-9]+']
        
